REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_admin(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.is_teacher(uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.teacher_has_class(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.can_view_student(uuid, uuid) FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM anon, authenticated, public;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_teacher(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.teacher_has_class(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_view_student(uuid, uuid) TO authenticated;